### PR TITLE
add --with-comments to preserve comments when returning an attribute

### LINKED ISSUE #102: allow comments to be preserved when using `hcledit attribute get`
When attempting to retrieve complex values using `attribute get` comments are stripped from the output. Would be nice if there was an option to preserve comments on `attribute get`

```terraform
locals {
  map = {
    # comment
    attribute = 1
  }
}
```

```
$ hcledit -f main.tf attribute get locals.map          
{

    attribute = 1
  }

```

for contrast, when retrieving blocks comments are preserved

```
$ hcledit -f main.tf block get locals    
locals {
  map = {
    # comment
    attribute = 1
  }
}
```

I've written some tooling using hcledit to emulate getting deeply nested attributes and it works well on retrieval, but when using that same tooling to set deeply nested attributes I end up stripping comments which is not ideal.

Can see how having comments removed is a very reasonable default expectation here (especially for same line comments), but would be nice if there was a flag to preserve comments when getting an attribute value.

### PR DESCRIPTION
**Pull request by wondersd**
fixes #102 

Only returns comments when attribute value is a block. Not sure whats missing to capture inline comments. However for the purposes of the original request this would be close enough

### CODE REVIEW

**Comment by minamijoyo** [comment]
Thanks for working on this. Overall, it looks good, but let me point out a few things.

(1) The linter check is failing. Some files need to be formatted.

(2) Although this cannot be strictly checked in the linter, the Go style convention recommends MixedCaps. That is to say, `withComments` seems more natural than `withcomments` for local variable names.

(3) Regarding being unable to get inline comments, they may belong to an attribute rather than an expression. I'll look into this later, but is this essential for your use case? I am unsure if I can find the time to look into it right away.

**Comment by wondersd** [comment]
Thanks for looking at this. I was going to go with `withComments` but everything else in the repo seemed to stick to lower so went with `withcomments`, will change and fix formatting.

For inline comments it doesn't matter for my purposes, i just considered it for completeness sake. If this goes out as is should we consider `--with-comments-on-blocks` to not make this a breaking change when inline comments are able to be accounted for?

**Comment by minamijoyo** [comment]
Thank you for the fix! I'll investigate the inline comments issue later, but I believe it would be technically possible without breaking the CLI interface, so there is no need to rename the flag. Let's merge and move forward!

**Review by minamijoyo — APPROVED** [review]
LGTM 👍

**Comment by minamijoyo** [comment]
@wondersd I've shipped it in v0.2.14 🚀  Thank you for your contribution!

**Pull request merged**
